//ESTE ARCHIVO SE UTILIZA PARA DECLARAR LOS TIPOS DE LOS ARCHIVOS CSS, YA QUE POR DEFECTO TYPESCRIPT NO LOS RECONOCE Y NOS DA UN ERROR CUANDO INTENTAMOS IMPORTAR UN ARCHIVO CSS EN NUESTRO PROYECTO. CON ESTA DECLARACIÓN LE DECIMOS A TYPESCRIPT QUE CUANDO VEA UNA IMPORTACIÓN DE UN ARCHIVO CSS, LO TRATE COMO UN MÓDULO QUE EXPORTA UN OBJETO CUYAS CLAVES SON LOS NOMBRES DE LAS CLASES CSS Y SUS VALORES SON LOS NOMBRES DE LAS CLASES GENERADOS POR EL PROCESO DE BUILD.

declare module '*.css' {
  const content: { [className: string]: string };
  export default content;
}

declare module 'swiper/css';
declare module 'swiper/css/*';